Enable building of source RPMS.

diff --git a/fakeprovide b/fakeprovide
--- a/fakeprovide
+++ b/fakeprovide
@@ -3,15 +3,26 @@
 # This script will generate an RPM that "provides" a named dependency.
 
 RPM_BUILDARCH=noarch
+RPM_SUMMARY=
+RPM_BUILD_SOURCE=0
+RPM_BUILD_BINARY=1
 
-usage () {
-	echo "$0: usage: $0 [ -a arch ] [ -s summary ] name"
+die () {
+	echo "$0: ERROR: $1" >&2
+	[ "$2" ] && cat "$2" >&2
+	exit 1
 }
 
-while getopts 'a:s:h' ch; do
+usage () {
+	echo "$0: usage: $0 [ -a arch ] [ -s summary ] [ -BS ] name"
+}
+
+while getopts 'a:s:hSB' ch; do
 	case $ch in
 		(a)	RPM_BUILDARCH="$OPTARG";;
 		(s)	RPM_SUMMARY="$OPTARG";;
+		(S)	RPM_BUILD_SOURCE=1;;
+		(B)	RPM_BUILD_BINARY=0;;
 		(h)	usage
 			exit 0
 			;;
@@ -21,6 +32,7 @@ while getopts 'a:s:h' ch; do
 			;;
 	esac
 done
+shift $(( $OPTIND - 1 ))
 
 tmpdir=$(mktemp -d --tmpdir rpmspecXXXXXX)
 trap "rm -rf $tmpdir" EXIT INT QUIT TERM HUP
@@ -35,8 +47,6 @@ fi
 mkdir -p $tmpdir/rpmbuild/SOURCES
 cat > $tmpdir/rpmbuild/SOURCES/README <<EOF
 This package was generated by fakeprovide.
-
-- http://github.com/larsks/fakeprovide/
 EOF
 
 cat > $tmpdir/fakeprovide.spec <<EOF
@@ -58,9 +68,10 @@ BuildArch:	$RPM_BUILDARCH
 %{summary}
 
 %prep
-
+%setup -c -T
 
 %build
+cp %{SOURCE0} .
 
 
 %install
@@ -82,8 +93,20 @@ rm -rf $RPM_BUILD_ROOT
 EOF
 
 export HOME=$tmpdir
-rpmbuild -bb $tmpdir/fakeprovide.spec > $tmpdir/log 2>&1
-for rpm in $tmpdir/rpmbuild/RPMS/*/*.rpm; do
+
+if [ "$RPM_BUILD_SOURCE" = 1 ]; then
+	echo "Building source RPM (SRPM)."
+	rpmbuild -bs $tmpdir/fakeprovide.spec > $tmpdir/srpm.log 2>&1 ||
+		die "Failed to build source RPM." $tmpdir/srpm.log
+fi
+
+if [ "$RPM_BUILD_BINARY" = 1 ]; then
+	echo "Building binary RPM."
+	rpmbuild -bb $tmpdir/fakeprovide.spec > $tmpdir/rpm.log 2>&1 ||
+		die "Failed to build binary RPM." $tmpdir/rpm.log
+fi
+
+for rpm in $tmpdir/rpmbuild/RPMS/*/*.rpm $tmpdir/rpmbuild/SRPMS/*.rpm; do
 	[ -f "$rpm" ] || continue
 
 	cp "$rpm" .
